// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: eventsub.proto

package twitch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageTypeEventSub int32

const (
	MessageTypeEventSub_TYPE_UNSPECIFIED                 MessageTypeEventSub = 0
	MessageTypeEventSub_TYPE_EVENTSUB_EVENT              MessageTypeEventSub = 1
	MessageTypeEventSub_TYPE_CHANNEL_RAID                MessageTypeEventSub = 2
	MessageTypeEventSub_TYPE_CHANNEL_FOLLOW              MessageTypeEventSub = 3
	MessageTypeEventSub_TYPE_CHANNEL_CHEER               MessageTypeEventSub = 4
	MessageTypeEventSub_TYPE_CHANNEL_POINT_CUSTOM_REDEEM MessageTypeEventSub = 5
	MessageTypeEventSub_TYPE_CHANNEL_CHAT_MESSAGE        MessageTypeEventSub = 6
)

// Enum value maps for MessageTypeEventSub.
var (
	MessageTypeEventSub_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_EVENTSUB_EVENT",
		2: "TYPE_CHANNEL_RAID",
		3: "TYPE_CHANNEL_FOLLOW",
		4: "TYPE_CHANNEL_CHEER",
		5: "TYPE_CHANNEL_POINT_CUSTOM_REDEEM",
		6: "TYPE_CHANNEL_CHAT_MESSAGE",
	}
	MessageTypeEventSub_value = map[string]int32{
		"TYPE_UNSPECIFIED":                 0,
		"TYPE_EVENTSUB_EVENT":              1,
		"TYPE_CHANNEL_RAID":                2,
		"TYPE_CHANNEL_FOLLOW":              3,
		"TYPE_CHANNEL_CHEER":               4,
		"TYPE_CHANNEL_POINT_CUSTOM_REDEEM": 5,
		"TYPE_CHANNEL_CHAT_MESSAGE":        6,
	}
)

func (x MessageTypeEventSub) Enum() *MessageTypeEventSub {
	p := new(MessageTypeEventSub)
	*p = x
	return p
}

func (x MessageTypeEventSub) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageTypeEventSub) Descriptor() protoreflect.EnumDescriptor {
	return file_eventsub_proto_enumTypes[0].Descriptor()
}

func (MessageTypeEventSub) Type() protoreflect.EnumType {
	return &file_eventsub_proto_enumTypes[0]
}

func (x MessageTypeEventSub) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageTypeEventSub.Descriptor instead.
func (MessageTypeEventSub) EnumDescriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{0}
}

type EventSubStatus int32

const (
	EventSubStatus_EVENT_SUB_STATUS_UNKNOWN   EventSubStatus = 0
	EventSubStatus_EVENT_SUB_STATUS_OFF       EventSubStatus = 1
	EventSubStatus_EVENT_SUB_STATUS_CONNECTED EventSubStatus = 2
	EventSubStatus_EVENT_SUB_STATUS_ERROR     EventSubStatus = 3
)

// Enum value maps for EventSubStatus.
var (
	EventSubStatus_name = map[int32]string{
		0: "EVENT_SUB_STATUS_UNKNOWN",
		1: "EVENT_SUB_STATUS_OFF",
		2: "EVENT_SUB_STATUS_CONNECTED",
		3: "EVENT_SUB_STATUS_ERROR",
	}
	EventSubStatus_value = map[string]int32{
		"EVENT_SUB_STATUS_UNKNOWN":   0,
		"EVENT_SUB_STATUS_OFF":       1,
		"EVENT_SUB_STATUS_CONNECTED": 2,
		"EVENT_SUB_STATUS_ERROR":     3,
	}
)

func (x EventSubStatus) Enum() *EventSubStatus {
	p := new(EventSubStatus)
	*p = x
	return p
}

func (x EventSubStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventSubStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_eventsub_proto_enumTypes[1].Descriptor()
}

func (EventSubStatus) Type() protoreflect.EnumType {
	return &file_eventsub_proto_enumTypes[1]
}

func (x EventSubStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventSubStatus.Descriptor instead.
func (EventSubStatus) EnumDescriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{1}
}

type ChatMessageFragmentType int32

const (
	ChatMessageFragmentType_text      ChatMessageFragmentType = 0
	ChatMessageFragmentType_cheermote ChatMessageFragmentType = 1
	ChatMessageFragmentType_emote     ChatMessageFragmentType = 2
	ChatMessageFragmentType_mention   ChatMessageFragmentType = 3
)

// Enum value maps for ChatMessageFragmentType.
var (
	ChatMessageFragmentType_name = map[int32]string{
		0: "text",
		1: "cheermote",
		2: "emote",
		3: "mention",
	}
	ChatMessageFragmentType_value = map[string]int32{
		"text":      0,
		"cheermote": 1,
		"emote":     2,
		"mention":   3,
	}
)

func (x ChatMessageFragmentType) Enum() *ChatMessageFragmentType {
	p := new(ChatMessageFragmentType)
	*p = x
	return p
}

func (x ChatMessageFragmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMessageFragmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_eventsub_proto_enumTypes[2].Descriptor()
}

func (ChatMessageFragmentType) Type() protoreflect.EnumType {
	return &file_eventsub_proto_enumTypes[2]
}

func (x ChatMessageFragmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMessageFragmentType.Descriptor instead.
func (ChatMessageFragmentType) EnumDescriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{2}
}

type ChatMessageType int32

const (
	ChatMessageType_chat_message_type_text                       ChatMessageType = 0
	ChatMessageType_chat_message_type_channel_points_highlighted ChatMessageType = 1
	ChatMessageType_chat_message_type_channel_points_sub_only    ChatMessageType = 2
	ChatMessageType_chat_message_type_user_intro                 ChatMessageType = 3
)

// Enum value maps for ChatMessageType.
var (
	ChatMessageType_name = map[int32]string{
		0: "chat_message_type_text",
		1: "chat_message_type_channel_points_highlighted",
		2: "chat_message_type_channel_points_sub_only",
		3: "chat_message_type_user_intro",
	}
	ChatMessageType_value = map[string]int32{
		"chat_message_type_text":                       0,
		"chat_message_type_channel_points_highlighted": 1,
		"chat_message_type_channel_points_sub_only":    2,
		"chat_message_type_user_intro":                 3,
	}
)

func (x ChatMessageType) Enum() *ChatMessageType {
	p := new(ChatMessageType)
	*p = x
	return p
}

func (x ChatMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_eventsub_proto_enumTypes[3].Descriptor()
}

func (ChatMessageType) Type() protoreflect.EnumType {
	return &file_eventsub_proto_enumTypes[3]
}

func (x ChatMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMessageType.Descriptor instead.
func (ChatMessageType) EnumDescriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{3}
}

type EventSubStatusEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status EventSubStatus `protobuf:"varint,1,opt,name=status,proto3,enum=twitch.EventSubStatus" json:"status,omitempty"`
	Detail string         `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *EventSubStatusEvent) Reset() {
	*x = EventSubStatusEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventSubStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubStatusEvent) ProtoMessage() {}

func (x *EventSubStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubStatusEvent.ProtoReflect.Descriptor instead.
func (*EventSubStatusEvent) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{0}
}

func (x *EventSubStatusEvent) GetStatus() EventSubStatus {
	if x != nil {
		return x.Status
	}
	return EventSubStatus_EVENT_SUB_STATUS_UNKNOWN
}

func (x *EventSubStatusEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type EventSubConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled   bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Profile   string `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	LogEvents bool   `protobuf:"varint,3,opt,name=log_events,json=logEvents,proto3" json:"log_events,omitempty"`
}

func (x *EventSubConfig) Reset() {
	*x = EventSubConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventSubConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubConfig) ProtoMessage() {}

func (x *EventSubConfig) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubConfig.ProtoReflect.Descriptor instead.
func (*EventSubConfig) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{1}
}

func (x *EventSubConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EventSubConfig) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *EventSubConfig) GetLogEvents() bool {
	if x != nil {
		return x.LogEvents
	}
	return false
}

type EventUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *EventUser) Reset() {
	*x = EventUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventUser) ProtoMessage() {}

func (x *EventUser) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventUser.ProtoReflect.Descriptor instead.
func (*EventUser) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{2}
}

func (x *EventUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventUser) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *EventUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EventChannelCheer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAnonymous *bool      `protobuf:"varint,1,opt,name=is_anonymous,json=isAnonymous,proto3,oneof" json:"is_anonymous,omitempty"`
	From        *EventUser `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Broadcaster *EventUser `protobuf:"bytes,3,opt,name=broadcaster,proto3" json:"broadcaster,omitempty"`
	Message     *string    `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Bits        uint32     `protobuf:"varint,5,opt,name=bits,proto3" json:"bits,omitempty"`
}

func (x *EventChannelCheer) Reset() {
	*x = EventChannelCheer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventChannelCheer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventChannelCheer) ProtoMessage() {}

func (x *EventChannelCheer) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventChannelCheer.ProtoReflect.Descriptor instead.
func (*EventChannelCheer) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{3}
}

func (x *EventChannelCheer) GetIsAnonymous() bool {
	if x != nil && x.IsAnonymous != nil {
		return *x.IsAnonymous
	}
	return false
}

func (x *EventChannelCheer) GetFrom() *EventUser {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EventChannelCheer) GetBroadcaster() *EventUser {
	if x != nil {
		return x.Broadcaster
	}
	return nil
}

func (x *EventChannelCheer) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *EventChannelCheer) GetBits() uint32 {
	if x != nil {
		return x.Bits
	}
	return 0
}

type EventChannelFollow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Follower    *EventUser `protobuf:"bytes,1,opt,name=follower,proto3" json:"follower,omitempty"`
	Broadcaster *EventUser `protobuf:"bytes,2,opt,name=broadcaster,proto3" json:"broadcaster,omitempty"`
	At          int64      `protobuf:"varint,3,opt,name=at,proto3" json:"at,omitempty"`
}

func (x *EventChannelFollow) Reset() {
	*x = EventChannelFollow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventChannelFollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventChannelFollow) ProtoMessage() {}

func (x *EventChannelFollow) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventChannelFollow.ProtoReflect.Descriptor instead.
func (*EventChannelFollow) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{4}
}

func (x *EventChannelFollow) GetFollower() *EventUser {
	if x != nil {
		return x.Follower
	}
	return nil
}

func (x *EventChannelFollow) GetBroadcaster() *EventUser {
	if x != nil {
		return x.Broadcaster
	}
	return nil
}

func (x *EventChannelFollow) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

type Reward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cost   int32  `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	Prompt string `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *Reward) Reset() {
	*x = Reward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reward) ProtoMessage() {}

func (x *Reward) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reward.ProtoReflect.Descriptor instead.
func (*Reward) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{5}
}

func (x *Reward) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reward) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Reward) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Reward) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type EventChannelPointsCustomRewardRedemption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Broadcaster *EventUser `protobuf:"bytes,2,opt,name=broadcaster,proto3" json:"broadcaster,omitempty"`
	User        *EventUser `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Input       string     `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Status      string     `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Reward      *Reward    `protobuf:"bytes,6,opt,name=reward,proto3" json:"reward,omitempty"`
	RedeemedAt  int64      `protobuf:"varint,7,opt,name=redeemed_at,json=redeemedAt,proto3" json:"redeemed_at,omitempty"`
}

func (x *EventChannelPointsCustomRewardRedemption) Reset() {
	*x = EventChannelPointsCustomRewardRedemption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventChannelPointsCustomRewardRedemption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventChannelPointsCustomRewardRedemption) ProtoMessage() {}

func (x *EventChannelPointsCustomRewardRedemption) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventChannelPointsCustomRewardRedemption.ProtoReflect.Descriptor instead.
func (*EventChannelPointsCustomRewardRedemption) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{6}
}

func (x *EventChannelPointsCustomRewardRedemption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventChannelPointsCustomRewardRedemption) GetBroadcaster() *EventUser {
	if x != nil {
		return x.Broadcaster
	}
	return nil
}

func (x *EventChannelPointsCustomRewardRedemption) GetUser() *EventUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *EventChannelPointsCustomRewardRedemption) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *EventChannelPointsCustomRewardRedemption) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EventChannelPointsCustomRewardRedemption) GetReward() *Reward {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *EventChannelPointsCustomRewardRedemption) GetRedeemedAt() int64 {
	if x != nil {
		return x.RedeemedAt
	}
	return 0
}

type EventChannelRaid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromBroadcaster *EventUser `protobuf:"bytes,1,opt,name=from_broadcaster,json=fromBroadcaster,proto3" json:"from_broadcaster,omitempty"`
	ToBroadcaster   *EventUser `protobuf:"bytes,2,opt,name=to_broadcaster,json=toBroadcaster,proto3" json:"to_broadcaster,omitempty"`
	Viewers         uint32     `protobuf:"varint,3,opt,name=viewers,proto3" json:"viewers,omitempty"`
}

func (x *EventChannelRaid) Reset() {
	*x = EventChannelRaid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventChannelRaid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventChannelRaid) ProtoMessage() {}

func (x *EventChannelRaid) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventChannelRaid.ProtoReflect.Descriptor instead.
func (*EventChannelRaid) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{7}
}

func (x *EventChannelRaid) GetFromBroadcaster() *EventUser {
	if x != nil {
		return x.FromBroadcaster
	}
	return nil
}

func (x *EventChannelRaid) GetToBroadcaster() *EventUser {
	if x != nil {
		return x.ToBroadcaster
	}
	return nil
}

func (x *EventChannelRaid) GetViewers() uint32 {
	if x != nil {
		return x.Viewers
	}
	return 0
}

type ChatMessageCheermote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Bits   int64  `protobuf:"varint,2,opt,name=bits,proto3" json:"bits,omitempty"`
	Tier   int32  `protobuf:"varint,3,opt,name=tier,proto3" json:"tier,omitempty"`
}

func (x *ChatMessageCheermote) Reset() {
	*x = ChatMessageCheermote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessageCheermote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageCheermote) ProtoMessage() {}

func (x *ChatMessageCheermote) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageCheermote.ProtoReflect.Descriptor instead.
func (*ChatMessageCheermote) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{8}
}

func (x *ChatMessageCheermote) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ChatMessageCheermote) GetBits() int64 {
	if x != nil {
		return x.Bits
	}
	return 0
}

func (x *ChatMessageCheermote) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

type ChatMessageEmote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EmoteSetId string   `protobuf:"bytes,2,opt,name=emote_set_id,json=emoteSetId,proto3" json:"emote_set_id,omitempty"`
	OwnerId    string   `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Format     []string `protobuf:"bytes,4,rep,name=format,proto3" json:"format,omitempty"`
}

func (x *ChatMessageEmote) Reset() {
	*x = ChatMessageEmote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessageEmote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageEmote) ProtoMessage() {}

func (x *ChatMessageEmote) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageEmote.ProtoReflect.Descriptor instead.
func (*ChatMessageEmote) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{9}
}

func (x *ChatMessageEmote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatMessageEmote) GetEmoteSetId() string {
	if x != nil {
		return x.EmoteSetId
	}
	return ""
}

func (x *ChatMessageEmote) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ChatMessageEmote) GetFormat() []string {
	if x != nil {
		return x.Format
	}
	return nil
}

type ChatMessageFragment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      ChatMessageFragmentType `protobuf:"varint,1,opt,name=type,proto3,enum=twitch.ChatMessageFragmentType" json:"type,omitempty"`
	Text      string                  `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Cheermote *ChatMessageCheermote   `protobuf:"bytes,3,opt,name=cheermote,proto3" json:"cheermote,omitempty"`
	Emote     *ChatMessageEmote       `protobuf:"bytes,4,opt,name=emote,proto3" json:"emote,omitempty"`
	Mention   *EventUser              `protobuf:"bytes,5,opt,name=mention,proto3" json:"mention,omitempty"`
}

func (x *ChatMessageFragment) Reset() {
	*x = ChatMessageFragment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessageFragment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageFragment) ProtoMessage() {}

func (x *ChatMessageFragment) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageFragment.ProtoReflect.Descriptor instead.
func (*ChatMessageFragment) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{10}
}

func (x *ChatMessageFragment) GetType() ChatMessageFragmentType {
	if x != nil {
		return x.Type
	}
	return ChatMessageFragmentType_text
}

func (x *ChatMessageFragment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessageFragment) GetCheermote() *ChatMessageCheermote {
	if x != nil {
		return x.Cheermote
	}
	return nil
}

func (x *ChatMessageFragment) GetEmote() *ChatMessageEmote {
	if x != nil {
		return x.Emote
	}
	return nil
}

func (x *ChatMessageFragment) GetMention() *EventUser {
	if x != nil {
		return x.Mention
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text      string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Fragments []*ChatMessageFragment `protobuf:"bytes,2,rep,name=fragments,proto3" json:"fragments,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{11}
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetFragments() []*ChatMessageFragment {
	if x != nil {
		return x.Fragments
	}
	return nil
}

type ChatBadge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SetId string `protobuf:"bytes,1,opt,name=set_id,json=setId,proto3" json:"set_id,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Info  string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ChatBadge) Reset() {
	*x = ChatBadge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatBadge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatBadge) ProtoMessage() {}

func (x *ChatBadge) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatBadge.ProtoReflect.Descriptor instead.
func (*ChatBadge) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{12}
}

func (x *ChatBadge) GetSetId() string {
	if x != nil {
		return x.SetId
	}
	return ""
}

func (x *ChatBadge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatBadge) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type ChatMessageCheer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bits int64 `protobuf:"varint,1,opt,name=bits,proto3" json:"bits,omitempty"`
}

func (x *ChatMessageCheer) Reset() {
	*x = ChatMessageCheer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessageCheer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageCheer) ProtoMessage() {}

func (x *ChatMessageCheer) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageCheer.ProtoReflect.Descriptor instead.
func (*ChatMessageCheer) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{13}
}

func (x *ChatMessageCheer) GetBits() int64 {
	if x != nil {
		return x.Bits
	}
	return 0
}

type ChatMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParentMessageId   string     `protobuf:"bytes,1,opt,name=parent_message_id,json=parentMessageId,proto3" json:"parent_message_id,omitempty"`
	ParentMessageBody string     `protobuf:"bytes,2,opt,name=parent_message_body,json=parentMessageBody,proto3" json:"parent_message_body,omitempty"`
	ParentUser        *EventUser `protobuf:"bytes,3,opt,name=parent_user,json=parentUser,proto3" json:"parent_user,omitempty"`
	ThreadMessageId   string     `protobuf:"bytes,4,opt,name=thread_message_id,json=threadMessageId,proto3" json:"thread_message_id,omitempty"`
	ThreadUser        *EventUser `protobuf:"bytes,5,opt,name=thread_user,json=threadUser,proto3" json:"thread_user,omitempty"`
}

func (x *ChatMessageReply) Reset() {
	*x = ChatMessageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageReply) ProtoMessage() {}

func (x *ChatMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageReply.ProtoReflect.Descriptor instead.
func (*ChatMessageReply) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{14}
}

func (x *ChatMessageReply) GetParentMessageId() string {
	if x != nil {
		return x.ParentMessageId
	}
	return ""
}

func (x *ChatMessageReply) GetParentMessageBody() string {
	if x != nil {
		return x.ParentMessageBody
	}
	return ""
}

func (x *ChatMessageReply) GetParentUser() *EventUser {
	if x != nil {
		return x.ParentUser
	}
	return nil
}

func (x *ChatMessageReply) GetThreadMessageId() string {
	if x != nil {
		return x.ThreadMessageId
	}
	return ""
}

func (x *ChatMessageReply) GetThreadUser() *EventUser {
	if x != nil {
		return x.ThreadUser
	}
	return nil
}

type EventChannelChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                          string                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Broadcaster                 *EventUser                           `protobuf:"bytes,2,opt,name=broadcaster,proto3" json:"broadcaster,omitempty"`
	Chatter                     *EventUser                           `protobuf:"bytes,3,opt,name=chatter,proto3" json:"chatter,omitempty"`
	Message                     *ChatMessage                         `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	MessageType                 ChatMessageType                      `protobuf:"varint,5,opt,name=message_type,json=messageType,proto3,enum=twitch.ChatMessageType" json:"message_type,omitempty"`
	Badges                      []*ChatBadge                         `protobuf:"bytes,6,rep,name=badges,proto3" json:"badges,omitempty"`
	Cheer                       *ChatMessageCheer                    `protobuf:"bytes,7,opt,name=cheer,proto3" json:"cheer,omitempty"`
	Color                       string                               `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	Reply                       *ChatMessageReply                    `protobuf:"bytes,9,opt,name=reply,proto3" json:"reply,omitempty"`
	ChannelPointsCustomRewardId string                               `protobuf:"bytes,10,opt,name=channel_points_custom_reward_id,json=channelPointsCustomRewardId,proto3" json:"channel_points_custom_reward_id,omitempty"`
	Enrichments                 *EventChannelChatMessage_Enrichments `protobuf:"bytes,11,opt,name=enrichments,proto3" json:"enrichments,omitempty"`
}

func (x *EventChannelChatMessage) Reset() {
	*x = EventChannelChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventChannelChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventChannelChatMessage) ProtoMessage() {}

func (x *EventChannelChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventChannelChatMessage.ProtoReflect.Descriptor instead.
func (*EventChannelChatMessage) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{15}
}

func (x *EventChannelChatMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventChannelChatMessage) GetBroadcaster() *EventUser {
	if x != nil {
		return x.Broadcaster
	}
	return nil
}

func (x *EventChannelChatMessage) GetChatter() *EventUser {
	if x != nil {
		return x.Chatter
	}
	return nil
}

func (x *EventChannelChatMessage) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *EventChannelChatMessage) GetMessageType() ChatMessageType {
	if x != nil {
		return x.MessageType
	}
	return ChatMessageType_chat_message_type_text
}

func (x *EventChannelChatMessage) GetBadges() []*ChatBadge {
	if x != nil {
		return x.Badges
	}
	return nil
}

func (x *EventChannelChatMessage) GetCheer() *ChatMessageCheer {
	if x != nil {
		return x.Cheer
	}
	return nil
}

func (x *EventChannelChatMessage) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *EventChannelChatMessage) GetReply() *ChatMessageReply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *EventChannelChatMessage) GetChannelPointsCustomRewardId() string {
	if x != nil {
		return x.ChannelPointsCustomRewardId
	}
	return ""
}

func (x *EventChannelChatMessage) GetEnrichments() *EventChannelChatMessage_Enrichments {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

type EventChannelChatMessage_Enrichments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsMod bool `protobuf:"varint,1,opt,name=is_mod,json=isMod,proto3" json:"is_mod,omitempty"`
}

func (x *EventChannelChatMessage_Enrichments) Reset() {
	*x = EventChannelChatMessage_Enrichments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventsub_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventChannelChatMessage_Enrichments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventChannelChatMessage_Enrichments) ProtoMessage() {}

func (x *EventChannelChatMessage_Enrichments) ProtoReflect() protoreflect.Message {
	mi := &file_eventsub_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventChannelChatMessage_Enrichments.ProtoReflect.Descriptor instead.
func (*EventChannelChatMessage_Enrichments) Descriptor() ([]byte, []int) {
	return file_eventsub_proto_rawDescGZIP(), []int{15, 0}
}

func (x *EventChannelChatMessage_Enrichments) GetIsMod() bool {
	if x != nil {
		return x.IsMod
	}
	return false
}

var File_eventsub_proto protoreflect.FileDescriptor

var file_eventsub_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x22, 0x5d, 0x0a, 0x13, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x53, 0x75, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x75,
	0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x63, 0x0a, 0x0e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x53, 0x75, 0x62, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x6c, 0x6f, 0x67, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x45, 0x0a, 0x09,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xe7, 0x01, 0x0a, 0x11, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x68, 0x65, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0c, 0x69, 0x73, 0x5f,
	0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x0b, 0x69, 0x73, 0x41, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x88, 0x01,
	0x01, 0x12, 0x25, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x33, 0x0a, 0x0b, 0x62, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x0b, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x69, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x62, 0x69, 0x74, 0x73,
	0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x69, 0x73, 0x5f, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75,
	0x73, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x88, 0x01,
	0x0a, 0x12, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x2d, 0x0a, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x0b, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0b, 0x62, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x61, 0x74, 0x22, 0x5a, 0x0a, 0x06, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72,
	0x6f, 0x6d, 0x70, 0x74, 0x22, 0x8d, 0x02, 0x0a, 0x28, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x33, 0x0a, 0x0b, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0b, 0x62, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x74, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x2e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x64, 0x65, 0x65, 0x6d,
	0x65, 0x64, 0x41, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x10, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x61, 0x69, 0x64, 0x12, 0x3c, 0x0a, 0x10, 0x66, 0x72, 0x6f,
	0x6d, 0x5f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0f, 0x66, 0x72, 0x6f, 0x6d, 0x42, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0e, 0x74, 0x6f, 0x5f, 0x62, 0x72,
	0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x0d, 0x74, 0x6f, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x76, 0x69, 0x65, 0x77, 0x65, 0x72, 0x73, 0x22, 0x56, 0x0a, 0x14, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x65, 0x65, 0x72, 0x6d,
	0x6f, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x62, 0x69, 0x74, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74,
	0x69, 0x65, 0x72, 0x22, 0x77, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x45, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x5f, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0xf7, 0x01, 0x0a,
	0x13, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x72, 0x61, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x3a, 0x0a,
	0x09, 0x63, 0x68, 0x65, 0x65, 0x72, 0x6d, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x65, 0x65, 0x72, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x09,
	0x63, 0x68, 0x65, 0x65, 0x72, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6d, 0x6f,
	0x74, 0x65, 0x52, 0x05, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x65, 0x6e,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07, 0x6d,
	0x65, 0x6e, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x39, 0x0a, 0x09, 0x66, 0x72, 0x61,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x66, 0x72, 0x61, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x46, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x74, 0x42, 0x61, 0x64, 0x67,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x26, 0x0a, 0x10,
	0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x68, 0x65, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x62, 0x69, 0x74, 0x73, 0x22, 0x82, 0x02, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x32, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0a, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x68, 0x72,
	0x65, 0x61, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x0b, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0a, 0x74,
	0x68, 0x72, 0x65, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x22, 0xd2, 0x04, 0x0a, 0x17, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x0b, 0x62,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x07, 0x63, 0x68,
	0x61, 0x74, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x07,
	0x63, 0x68, 0x61, 0x74, 0x74, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x74,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x62, 0x61, 0x64, 0x67, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x42, 0x61, 0x64, 0x67, 0x65, 0x52, 0x06, 0x62, 0x61, 0x64, 0x67, 0x65, 0x73, 0x12, 0x2e, 0x0a,
	0x05, 0x63, 0x68, 0x65, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x43, 0x68, 0x65, 0x65, 0x72, 0x52, 0x05, 0x63, 0x68, 0x65, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x05, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x1f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x5f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1b, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12, 0x4d, 0x0a, 0x0b, 0x65, 0x6e, 0x72,
	0x69, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x45, 0x6e, 0x72, 0x69, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x0b, 0x65, 0x6e, 0x72,
	0x69, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x24, 0x0a, 0x0b, 0x45, 0x6e, 0x72, 0x69,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x6d, 0x6f,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x4d, 0x6f, 0x64, 0x2a, 0xd1,
	0x01, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x53, 0x55, 0x42, 0x5f, 0x45, 0x56,
	0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48,
	0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x52, 0x41, 0x49, 0x44, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x46, 0x4f, 0x4c,
	0x4c, 0x4f, 0x57, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48,
	0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x43, 0x48, 0x45, 0x45, 0x52, 0x10, 0x04, 0x12, 0x24, 0x0a,
	0x20, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x50, 0x4f,
	0x49, 0x4e, 0x54, 0x5f, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x5f, 0x52, 0x45, 0x44, 0x45, 0x45,
	0x4d, 0x10, 0x05, 0x12, 0x1d, 0x0a, 0x19, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e,
	0x4e, 0x45, 0x4c, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45,
	0x10, 0x06, 0x2a, 0x84, 0x01, 0x0a, 0x0e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x18, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53,
	0x55, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x55, 0x42,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x46, 0x46, 0x10, 0x01, 0x12, 0x1e, 0x0a,
	0x1a, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1a, 0x0a,
	0x16, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x55, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x2a, 0x4a, 0x0a, 0x17, 0x43, 0x68, 0x61,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x63, 0x68, 0x65, 0x65, 0x72, 0x6d, 0x6f, 0x74, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x6d, 0x65, 0x6e, 0x74,
	0x69, 0x6f, 0x6e, 0x10, 0x03, 0x2a, 0xb0, 0x01, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x63, 0x68, 0x61,
	0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x74,
	0x65, 0x78, 0x74, 0x10, 0x00, 0x12, 0x30, 0x0a, 0x2c, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x5f, 0x68, 0x69, 0x67, 0x68, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x2d, 0x0a, 0x29, 0x63, 0x68, 0x61, 0x74, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x5f, 0x73, 0x75, 0x62, 0x5f,
	0x6f, 0x6e, 0x6c, 0x79, 0x10, 0x02, 0x12, 0x20, 0x0a, 0x1c, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x10, 0x03, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x6f, 0x6d, 0x6f, 0x75,
	0x73, 0x6b, 0x6f, 0x69, 0x2f, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_eventsub_proto_rawDescOnce sync.Once
	file_eventsub_proto_rawDescData = file_eventsub_proto_rawDesc
)

func file_eventsub_proto_rawDescGZIP() []byte {
	file_eventsub_proto_rawDescOnce.Do(func() {
		file_eventsub_proto_rawDescData = protoimpl.X.CompressGZIP(file_eventsub_proto_rawDescData)
	})
	return file_eventsub_proto_rawDescData
}

var file_eventsub_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_eventsub_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_eventsub_proto_goTypes = []any{
	(MessageTypeEventSub)(0),                         // 0: twitch.MessageTypeEventSub
	(EventSubStatus)(0),                              // 1: twitch.EventSubStatus
	(ChatMessageFragmentType)(0),                     // 2: twitch.ChatMessageFragmentType
	(ChatMessageType)(0),                             // 3: twitch.ChatMessageType
	(*EventSubStatusEvent)(nil),                      // 4: twitch.EventSubStatusEvent
	(*EventSubConfig)(nil),                           // 5: twitch.EventSubConfig
	(*EventUser)(nil),                                // 6: twitch.EventUser
	(*EventChannelCheer)(nil),                        // 7: twitch.EventChannelCheer
	(*EventChannelFollow)(nil),                       // 8: twitch.EventChannelFollow
	(*Reward)(nil),                                   // 9: twitch.Reward
	(*EventChannelPointsCustomRewardRedemption)(nil), // 10: twitch.EventChannelPointsCustomRewardRedemption
	(*EventChannelRaid)(nil),                         // 11: twitch.EventChannelRaid
	(*ChatMessageCheermote)(nil),                     // 12: twitch.ChatMessageCheermote
	(*ChatMessageEmote)(nil),                         // 13: twitch.ChatMessageEmote
	(*ChatMessageFragment)(nil),                      // 14: twitch.ChatMessageFragment
	(*ChatMessage)(nil),                              // 15: twitch.ChatMessage
	(*ChatBadge)(nil),                                // 16: twitch.ChatBadge
	(*ChatMessageCheer)(nil),                         // 17: twitch.ChatMessageCheer
	(*ChatMessageReply)(nil),                         // 18: twitch.ChatMessageReply
	(*EventChannelChatMessage)(nil),                  // 19: twitch.EventChannelChatMessage
	(*EventChannelChatMessage_Enrichments)(nil),      // 20: twitch.EventChannelChatMessage.Enrichments
}
var file_eventsub_proto_depIdxs = []int32{
	1,  // 0: twitch.EventSubStatusEvent.status:type_name -> twitch.EventSubStatus
	6,  // 1: twitch.EventChannelCheer.from:type_name -> twitch.EventUser
	6,  // 2: twitch.EventChannelCheer.broadcaster:type_name -> twitch.EventUser
	6,  // 3: twitch.EventChannelFollow.follower:type_name -> twitch.EventUser
	6,  // 4: twitch.EventChannelFollow.broadcaster:type_name -> twitch.EventUser
	6,  // 5: twitch.EventChannelPointsCustomRewardRedemption.broadcaster:type_name -> twitch.EventUser
	6,  // 6: twitch.EventChannelPointsCustomRewardRedemption.user:type_name -> twitch.EventUser
	9,  // 7: twitch.EventChannelPointsCustomRewardRedemption.reward:type_name -> twitch.Reward
	6,  // 8: twitch.EventChannelRaid.from_broadcaster:type_name -> twitch.EventUser
	6,  // 9: twitch.EventChannelRaid.to_broadcaster:type_name -> twitch.EventUser
	2,  // 10: twitch.ChatMessageFragment.type:type_name -> twitch.ChatMessageFragmentType
	12, // 11: twitch.ChatMessageFragment.cheermote:type_name -> twitch.ChatMessageCheermote
	13, // 12: twitch.ChatMessageFragment.emote:type_name -> twitch.ChatMessageEmote
	6,  // 13: twitch.ChatMessageFragment.mention:type_name -> twitch.EventUser
	14, // 14: twitch.ChatMessage.fragments:type_name -> twitch.ChatMessageFragment
	6,  // 15: twitch.ChatMessageReply.parent_user:type_name -> twitch.EventUser
	6,  // 16: twitch.ChatMessageReply.thread_user:type_name -> twitch.EventUser
	6,  // 17: twitch.EventChannelChatMessage.broadcaster:type_name -> twitch.EventUser
	6,  // 18: twitch.EventChannelChatMessage.chatter:type_name -> twitch.EventUser
	15, // 19: twitch.EventChannelChatMessage.message:type_name -> twitch.ChatMessage
	3,  // 20: twitch.EventChannelChatMessage.message_type:type_name -> twitch.ChatMessageType
	16, // 21: twitch.EventChannelChatMessage.badges:type_name -> twitch.ChatBadge
	17, // 22: twitch.EventChannelChatMessage.cheer:type_name -> twitch.ChatMessageCheer
	18, // 23: twitch.EventChannelChatMessage.reply:type_name -> twitch.ChatMessageReply
	20, // 24: twitch.EventChannelChatMessage.enrichments:type_name -> twitch.EventChannelChatMessage.Enrichments
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_eventsub_proto_init() }
func file_eventsub_proto_init() {
	if File_eventsub_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eventsub_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EventSubStatusEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EventSubConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*EventUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*EventChannelCheer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EventChannelFollow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Reward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EventChannelPointsCustomRewardRedemption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*EventChannelRaid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ChatMessageCheermote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ChatMessageEmote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ChatMessageFragment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*ChatBadge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*ChatMessageCheer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ChatMessageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*EventChannelChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventsub_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*EventChannelChatMessage_Enrichments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_eventsub_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eventsub_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eventsub_proto_goTypes,
		DependencyIndexes: file_eventsub_proto_depIdxs,
		EnumInfos:         file_eventsub_proto_enumTypes,
		MessageInfos:      file_eventsub_proto_msgTypes,
	}.Build()
	File_eventsub_proto = out.File
	file_eventsub_proto_rawDesc = nil
	file_eventsub_proto_goTypes = nil
	file_eventsub_proto_depIdxs = nil
}
